steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "pull bucket data"
    waitFor: ["-"]
    args: ["storage", "rsync", "-r", "gs://data_bucket_lmu/data/", "data"]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "pull bucket modelweights"
    waitFor: ["-"]
    args:
      [
        "storage",
        "rsync",
        "-r",
        "gs://data_bucket_lmu/mlops_project/models/",
        "mlops_project/models",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "Build hatespeech-base image"
    waitFor: ["-"]
    args:
      [
        "build",
        ".",
        "-t",
        "hatespeech-base",
        "-f",
        "dockerfiles/hatespeech_base.dockerfile",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Build train container image"
    waitFor: ["Build hatespeech-base image"]
    args:
      [
        "build",
        ".",
        "-t",
        "europe-west3-docker.pkg.dev/$PROJECT_ID/hatespeech-detection-docker-repo/train-model",
        "-f",
        "dockerfiles/train_model.dockerfile",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Build inference api container image"
    waitFor: ["Build hatespeech-base image", "pull bucket modelweights"]
    args:
      [
        "build",
        ".",
        "-t",
        "europe-west3-docker.pkg.dev/$PROJECT_ID/hatespeech-detection-docker-repo/inference-api",
        "-f",
        "dockerfiles/inference_api.dockerfile",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "Build predict container image"
    waitFor:
      [
        "Build hatespeech-base image",
        "pull bucket modelweights",
        "pull bucket data",
      ]
    args:
      [
        "build",
        ".",
        "-t",
        "europe-west3-docker.pkg.dev/$PROJECT_ID/hatespeech-detection-docker-repo/predict-model",
        "-f",
        "dockerfiles/predict_model.dockerfile",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy inference api docker container to Cloud Run"
    waitFor: ["Build inference api container image"]
    args:
      [
        "run",
        "deploy",
        "hate-speech-detection-cloudrun-api",
        "--image",
        "europe-west3-docker.pkg.dev/lmumlops/hatespeech-detection-docker-repo/inference-api:latest",
        "--region",
        "europe-west3",
        "--platform",
        "managed",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "europe-west3-docker.pkg.dev/$PROJECT_ID/hatespeech-detection-docker-repo/train-model"
  - "europe-west3-docker.pkg.dev/$PROJECT_ID/hatespeech-detection-docker-repo/inference-api"
  - "europe-west3-docker.pkg.dev/$PROJECT_ID/hatespeech-detection-docker-repo/predict-model"
