program: train_model.py
name: sweep_best # Change sweep name
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  BATCH_SIZE:
    values: [16]
  EPOCHS:
    values: [7]
  LEARNING_RATE:
    values: [0.000005]
