program: train_model.py
name: sweep_XXX # Change sweep name
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  BATCH_SIZE:
    values: [16, 32]
  EPOCHS:
    values: [3, 5]
  LEARNING_RATE:
    values: [0.000001, 0.000005]
