program: train_model.py
name: reproducibility_sweep2 # Change sweep name
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  BATCH_SIZE:
    values: [32]
  EPOCHS:
    values: [3]
  LEARNING_RATE:
    values: [0.000005]
