program: train_model.py
name: first_sweep
method: random
metric:
  goal: minimize
  name: val_loss
parameters:
  BATCH_SIZE:
    values: [16, 32]
  EPOCHS:
    values: [2, 4]
  LEARNING_RATE:
    values: [0.00001, 0.000005]
