name: "Unit tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3
        # cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: iterative/setup-dvc@v1

    - name: Authenticate to GCP
      env:
        GCP_BUCKET_ACCOUNT_KEY: ${{ secrets.GCP_BUCKET_ACCOUNT_KEY }}
      run: |
        echo "$GCP_BUCKET_ACCOUNT_KEY" > $HOME/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json
        gcloud config set project lmumlops

    - name: Get data
      run: dvc pull -r gcloud

    - name: Test with pytest
      run: |
        pytest -v
