name: "Trigger cloudbuild"
on:
  pull_request:
    types:
      - closed

jobs:
  cloudbuild:
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_BUCKET_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: lmumlops

      - name: Submit build
        run: gcloud builds submit --config cloudbuild.yaml
